// permissions.js

const PERMISSIONS = {
  ORG_UPDATE: 'organization.update',
  ORG_DELETE: 'organization.delete',
  
  MEMBERS_READ: 'members.read',
  MEMBERS_INVITE: 'members.invite',
  MEMBERS_UPDATE: 'members.update',
  MEMBERS_REMOVE: 'members.remove',

  TEAMS_READ: 'teams.read',
  TEAMS_CREATE: 'teams.create',
  TEAMS_UPDATE: 'teams.update',
  TEAMS_DELETE: 'teams.delete',
  TEAMS_MANAGE_MEMBERS: 'teams.manage_members',
  
  TRAINING_READ: 'training.read',
  TRAINING_MANAGE: 'training.manage',

  REPORTS_READ: 'reports.read',
  REPORTS_EXPORT: 'reports.export',
  SECURITY_REPORTS_READ: 'security_reports.read',
  SECURITY_REPORTS_EXPORT: 'security_reports.export',

  SCANS_READ: 'scans.read',
  SCANS_MANAGE: 'scans.manage',

  AUDIT_READ: 'security_events.read',

  // Phase 10: Security Operations
  SECURITY_READ: 'security.read',
  SECURITY_MANAGE: 'security.manage',

  INCIDENTS_READ: 'incidents.read',
  INCIDENTS_CREATE: 'incidents.create',
  INCIDENTS_UPDATE: 'incidents.update',
  INCIDENTS_ASSIGN: 'incidents.assign',
  INCIDENTS_CLOSE: 'incidents.close',

  IOCS_READ: 'iocs.read',
  IOCS_CREATE: 'iocs.create',
  IOCS_UPDATE: 'iocs.update',
  IOCS_DELETE: 'iocs.delete',
  IOCS_ENRICH: 'iocs.enrich',

  INVESTIGATIONS_READ: 'investigations.read',
  INVESTIGATIONS_CREATE: 'investigations.create',
  INVESTIGATIONS_UPDATE: 'investigations.update',
  INVESTIGATIONS_CLOSE: 'investigations.close',

  CAMPAIGNS_READ: 'campaigns.read',
  CAMPAIGNS_CREATE: 'campaigns.create',
  CAMPAIGNS_UPDATE: 'campaigns.update',
  CAMPAIGNS_LAUNCH: 'campaigns.launch',
  CAMPAIGNS_PAUSE: 'campaigns.pause',
  CAMPAIGNS_CANCEL: 'campaigns.cancel',
  CAMPAIGNS_VIEW_RESULTS: 'campaigns.view_results',

  // Phase 11: Integrations and Platform
  INTEGRATIONS_READ: 'integrations.read',
  INTEGRATIONS_CREATE: 'integrations.create',
  INTEGRATIONS_UPDATE: 'integrations.update',
  INTEGRATIONS_DELETE: 'integrations.delete',
  INTEGRATIONS_TEST: 'integrations.test',
  
  WEBHOOKS_READ: 'webhooks.read',
  WEBHOOKS_CREATE: 'webhooks.create',
  WEBHOOKS_UPDATE: 'webhooks.update',
  WEBHOOKS_DELETE: 'webhooks.delete',
  
  API_KEYS_READ: 'apiKeys.read',
  API_KEYS_CREATE: 'apiKeys.create',
  API_KEYS_REVOKE: 'apiKeys.revoke',
  
  SERVICE_ACCOUNTS_READ: 'serviceAccounts.read',
  SERVICE_ACCOUNTS_CREATE: 'serviceAccounts.create',
  SERVICE_ACCOUNTS_UPDATE: 'serviceAccounts.update',
  SERVICE_ACCOUNTS_REVOKE: 'serviceAccounts.revoke',
  
  SIEM_READ: 'siem.read',
  SIEM_CONFIGURE: 'siem.configure',
  SIEM_TEST: 'siem.test',
  
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_CONFIGURE: 'notifications.configure',
  
  API_ACCESS: 'api.access'
};

const ROLES = {
  OWNER: 'Owner',
  ADMIN: 'Admin',
  MANAGER: 'Manager',
  MEMBER: 'Member',
  VIEWER: 'Viewer'
};

// Owner gets all automatically in hasPermission check to avoid missing any.
// Admin gets most but not owner operations like delete org.
const adminPerms = [
  PERMISSIONS.ORG_UPDATE,
  PERMISSIONS.MEMBERS_READ, PERMISSIONS.MEMBERS_INVITE, PERMISSIONS.MEMBERS_UPDATE, PERMISSIONS.MEMBERS_REMOVE,
  PERMISSIONS.TEAMS_READ, PERMISSIONS.TEAMS_CREATE, PERMISSIONS.TEAMS_UPDATE, PERMISSIONS.TEAMS_DELETE, PERMISSIONS.TEAMS_MANAGE_MEMBERS,
  PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_MANAGE,
  PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.SECURITY_REPORTS_READ, PERMISSIONS.SECURITY_REPORTS_EXPORT,
  PERMISSIONS.SCANS_READ, PERMISSIONS.SCANS_MANAGE,
  PERMISSIONS.AUDIT_READ,
  
  PERMISSIONS.SECURITY_READ, PERMISSIONS.SECURITY_MANAGE,
  PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE, PERMISSIONS.INCIDENTS_UPDATE, PERMISSIONS.INCIDENTS_ASSIGN, PERMISSIONS.INCIDENTS_CLOSE,
  PERMISSIONS.IOCS_READ, PERMISSIONS.IOCS_CREATE, PERMISSIONS.IOCS_UPDATE, PERMISSIONS.IOCS_DELETE, PERMISSIONS.IOCS_ENRICH,
  PERMISSIONS.INVESTIGATIONS_READ, PERMISSIONS.INVESTIGATIONS_CREATE, PERMISSIONS.INVESTIGATIONS_UPDATE, PERMISSIONS.INVESTIGATIONS_CLOSE,
  PERMISSIONS.CAMPAIGNS_READ, PERMISSIONS.CAMPAIGNS_CREATE, PERMISSIONS.CAMPAIGNS_UPDATE, PERMISSIONS.CAMPAIGNS_LAUNCH,
  PERMISSIONS.CAMPAIGNS_PAUSE, PERMISSIONS.CAMPAIGNS_CANCEL, PERMISSIONS.CAMPAIGNS_VIEW_RESULTS,

  PERMISSIONS.INTEGRATIONS_READ, PERMISSIONS.INTEGRATIONS_CREATE, PERMISSIONS.INTEGRATIONS_UPDATE, PERMISSIONS.INTEGRATIONS_DELETE, PERMISSIONS.INTEGRATIONS_TEST,
  PERMISSIONS.WEBHOOKS_READ, PERMISSIONS.WEBHOOKS_CREATE, PERMISSIONS.WEBHOOKS_UPDATE, PERMISSIONS.WEBHOOKS_DELETE,
  PERMISSIONS.API_KEYS_READ, PERMISSIONS.API_KEYS_CREATE, PERMISSIONS.API_KEYS_REVOKE,
  PERMISSIONS.SERVICE_ACCOUNTS_READ, PERMISSIONS.SERVICE_ACCOUNTS_CREATE, PERMISSIONS.SERVICE_ACCOUNTS_UPDATE, PERMISSIONS.SERVICE_ACCOUNTS_REVOKE,
  PERMISSIONS.SIEM_READ, PERMISSIONS.SIEM_CONFIGURE, PERMISSIONS.SIEM_TEST,
  PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_CONFIGURE,
  PERMISSIONS.API_ACCESS
];

const managerPerms = [
  PERMISSIONS.MEMBERS_READ,
  PERMISSIONS.TEAMS_READ, PERMISSIONS.TEAMS_CREATE, PERMISSIONS.TEAMS_UPDATE, PERMISSIONS.TEAMS_MANAGE_MEMBERS,
  PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_MANAGE,
  PERMISSIONS.REPORTS_READ, PERMISSIONS.SECURITY_REPORTS_READ,
  
  PERMISSIONS.SECURITY_READ,
  PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE, PERMISSIONS.INCIDENTS_UPDATE, PERMISSIONS.INCIDENTS_ASSIGN, PERMISSIONS.INCIDENTS_CLOSE,
  PERMISSIONS.IOCS_READ, PERMISSIONS.IOCS_CREATE, PERMISSIONS.IOCS_UPDATE, PERMISSIONS.IOCS_ENRICH,
  PERMISSIONS.INVESTIGATIONS_READ, PERMISSIONS.INVESTIGATIONS_CREATE, PERMISSIONS.INVESTIGATIONS_UPDATE, PERMISSIONS.INVESTIGATIONS_CLOSE,
  PERMISSIONS.CAMPAIGNS_READ, PERMISSIONS.CAMPAIGNS_CREATE, PERMISSIONS.CAMPAIGNS_UPDATE, PERMISSIONS.CAMPAIGNS_LAUNCH,
  PERMISSIONS.CAMPAIGNS_PAUSE, PERMISSIONS.CAMPAIGNS_CANCEL, PERMISSIONS.CAMPAIGNS_VIEW_RESULTS,

  PERMISSIONS.INTEGRATIONS_READ, PERMISSIONS.WEBHOOKS_READ, PERMISSIONS.SIEM_READ, PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.API_KEYS_READ, PERMISSIONS.API_KEYS_CREATE, PERMISSIONS.API_KEYS_REVOKE,
  PERMISSIONS.API_ACCESS
];

const memberPerms = [
  PERMISSIONS.MEMBERS_READ,
  PERMISSIONS.TEAMS_READ,
  PERMISSIONS.TRAINING_READ,
  PERMISSIONS.SECURITY_READ,
  PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
  PERMISSIONS.IOCS_READ, PERMISSIONS.IOCS_CREATE,
  PERMISSIONS.INVESTIGATIONS_READ,
  PERMISSIONS.CAMPAIGNS_READ,
  PERMISSIONS.API_ACCESS
];

const viewerPerms = [
  PERMISSIONS.MEMBERS_READ,
  PERMISSIONS.TEAMS_READ,
  PERMISSIONS.TRAINING_READ,
  PERMISSIONS.REPORTS_READ, PERMISSIONS.SECURITY_REPORTS_READ,
  PERMISSIONS.SECURITY_READ,
  PERMISSIONS.INCIDENTS_READ,
  PERMISSIONS.IOCS_READ,
  PERMISSIONS.INVESTIGATIONS_READ,
  PERMISSIONS.CAMPAIGNS_READ,
  PERMISSIONS.API_ACCESS
];

const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: adminPerms,
  [ROLES.MANAGER]: managerPerms,
  [ROLES.MEMBER]: memberPerms,
  [ROLES.VIEWER]: viewerPerms
};

function hasPermission(role, permission) {
  if (role === ROLES.OWNER) return true; // Owner implicitly has all permissions.
  const perms = ROLE_PERMISSIONS[role] || [];
  return perms.includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
  hasPermission
};
